SiliconMVC/ViewModels/SignUpViewModel.cs
using Infrastructure.Model;

namespace SiliconMVC.ViewModels
{
    public class SignUpViewModel
    {
        public string Title { get; set; } = "Sign up";

        public string? ErrorMessage { get; set; }
        
        public SignUpModel Form { get; set; } = new SignUpModel();
    }
}

SiliconMVC/Controllers/SignUpController.cs
using Infrastructure.Entities;
using Infrastructure.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace SiliconMVC.Controllers
{
    public class SignUpController : Controller
    {

        private readonly UserManager<UserEntity> _userManager;

        public SignUpController(UserManager<UserEntity> userManager)
        {
            _userManager = userManager;
        }

        public void SetDefaultValues()
        {
            ViewBag.ShowFooter = false;
            ViewBag.ShowChoices = false;
        }

        #region [HttpGet] SignUp
        //SIGN-UP
        [HttpGet]
        [Route("/signup")]
        public IActionResult Index()
        {
            var viewModel = new SignUpViewModel();
            SetDefaultValues();
            return View(viewModel);
        }
        #endregion

        [HttpPost]
        [Route("/signup")]
        public async Task<IActionResult> SignUp(SignUpViewModel viewModel)
        {
            SetDefaultValues();

            if (ModelState.IsValid)
            {
                var exist = await _userManager.Users.AnyAsync(x => x.Email == viewModel.Form.Email);

                if (exist == true)
                {
                    viewModel.ErrorMessage = "A user with the same email already exist";
                    return View(viewModel);
                }

                var userEntity = new UserEntity
                {
                    FirstName = viewModel.Form.FirstName,
                    LastName = viewModel.Form.LastName,
                    Email = viewModel.Form.Email,
                    UserName = viewModel.Form.Email,
                };

                var result = await _userManager.CreateAsync(userEntity, viewModel.Form.Password);

                if (result.Succeeded)
                {
                    var roleResult = await _userManager.AddToRoleAsync(userEntity, "User");

                    if(roleResult.Succeeded)
                    {
                        return RedirectToAction("SignIn", "Account");
                    }
                }
            }
            return View(viewModel);
        }
    }
}

SiliconMVC/Views/SignUp/Index.cshtml
@model Infrastructure.ViewModels.SignUpViewModel

@{
    ViewData["Title"] = "Sign up";
}

<section id="sign-up" class="">
    <div class="container">
        <form class="sign-in-form" method="post" asp-controller="SignUp" asp-action="SignUp" novalidate>
            <span>@Model.ErrorMessage</span>
            <div class="headlines">
                <h1>Create Account</h1>
                <p>Already have an account?<a asp-controller="SignIn" asp-action="Index"> Sign in here.</a></p>
            </div>
            <div class="name-box">
                <div id="form-firstname">
                    <label asp-for="Form.FirstName"><b>First name</b></label>
                    <span class="" asp-validation-for="Form.FirstName"></span>
                    <input asp-for="@Model.Form.FirstName" />
                </div>
                <div id="form-lastname">
                    <label asp-for="Form.LastName"><b>Last name</b></label>
                    <span asp-validation-for="Form.LastName" class=""></span>
                    <input asp-for="@Model.Form.LastName" />
                </div>
            </div>

            <div id="form-email">
                <label asp-for="@Model.Form.Email"><b>Email</b></label>
                <span asp-validation-for="@Model.Form.Email" class=""></span>
                <input asp-for="@Model.Form.Email" />
            </div>

            <div id="form-password">
                <label asp-for="@Model.Form.Password"><b>Password</b></label>
                <span asp-validation-for="@Model.Form.Password" class=""></span>
                <input id="password-signUp" asp-for="@Model.Form.Password" />
            </div>
            <div id="form-comfirm">
                <label asp-for="@Model.Form.ConfirmPassword"><b>Confirm password</b></label>
                <span asp-validation-for="@Model.Form.ConfirmPassword" class=""></span>
                <input id="confirmPassword-signUp" asp-for="@Model.Form.ConfirmPassword" />
            </div>
            <div class="form-check">
                <div>
                    <input asp-for="@Model.Form.TermsAndConditions" class="form-check-input" type="checkbox" id="flexCheckDefault">
                    <label asp-for="@Model.Form.TermsAndConditions" class="form-check-label" for="flexCheckDefault">
                        I agree to the <a asp-controller="About" asp-action="Terms">Terms</a> & <a asp-controller="About" asp-action="Conditions">Conditions</a>
                    </label>
                </div>
                <span id="termsspan" asp-validation-for="@Model.Form.TermsAndConditions" class=""></span>
            </div>

            <button class="btn-theme-s" type="submit">Sign in</button>
        </form>
    </div>
</section>

@await Html.PartialAsync("_ValidationScriptPartial")